### ISSUE TITLE
Thanks + help with avahi

### ISSUE THREAD

**Issue by shamoon** [dhutchison/container-images#1]
Hi, this is not so much an issue with your script, which seems to work great and I would like to thank you for it, but I had no other way to reach out. I seem to be having an issue where my avahi just stops advertising the Homebridge service (using Discovery app on a Mac) and then homebridge is of course unresponsive. Whats really bizarre is it kinda comes back on and off randomly but there is nothing in the avahi-daemon logs (they just show it running fine), the ports are open, etc. This actually happens even if docker is not running...

Again, I know this isnt really your script (I guess) but I'm at a loss...

Running ubuntu 20.04 LTS

Thanks for any thoughts, if not, I get it =)

**Comment by nikonratm** [comment]
Not really sure why, just kinda started working. Again, thanks for the awesome script + tutorial!

**Comment by shamoon** [comment]
Update: I could never get this to be stable, went with macvlan setup—took me a bit but seems all well. Thanks again for posting this though!

**Comment by dhutchison** [comment]
It does seem a bit unpredictable running in docker full stop. I have two homebridge instances running, one of them was setup with host networking (to make Wake on Lan work) and I still needed to use my script to make the avahi side of things work correctly. I've been meaning to revisit it but it isn't high on my priority list.

**Comment by shamoon** [comment]
Ha, yea this just turned into a bit of an obsessive project for me but ultimately macvlan seems more stable than any other option. Also apparently [homebridge is going to change its mdns implementation again](https://github.com/homebridge/homebridge/issues/2591#issuecomment-634643681) so who knows from there 🤷🏽‍♂️
