### ISSUE TITLE
sysctl: cannot stat /proc/sys/net/ipv4/conf/all/bc_forwarding: No such file or directory

### ISSUE THREAD

**Issue by bladerunner2020** [dhutchison/container-images#3]
I have few machines with Ubuntu 20.04 and this .sh works fine (thanks!), but today I encountered error on Ubuntu 18.04:
```bash
$: sudo sysctl -w net.ipv4.conf.all.bc_forwarding=1
sysctl: cannot stat /proc/sys/net/ipv4/conf/all/bc_forwarding: No such file or directory
```

Any ideas?

**Comment by dhutchison** [comment]
None I'm afraid. I think this approach depends on requiring a newer kernel version than 18.04 uses.
