### ISSUE TITLE
Reverse the code

### ISSUE THREAD

**Issue by kb8cb40j1av39c02** [dhutchison/container-images#4]
First of all, is it safe to use the script, or does allowing WOL-Packages to go through open some kind of security risk?
And also - how would I revert the process?

Thanks for your feedback!

**Comment by kb8cb40j1av39c02** [comment]
Sorry I should perhaps clarify: I'm talking about [this](https://github.com/dhutchison/container-images/blob/master/homebridge/configure_docker_networks_for_wol.sh) script of yours.

**Comment by dhutchison** [comment]
To revert it you can re-run the script with any "=0" replaced with "=1" (and vice versa), although I don't use this setup anymore and there is a suggestion in this issue that it no longer works - https://github.com/dhutchison/dhutchison.github.io/issues/9 . 

I'm not aware of any way this could be a security risk, but ultimately you need to decide what your risk/reward threshold is.
